version: "3.8"

networks:
  network:

services:
  broker:
    container_name: hivemq-ce
    image: hivemq/hivemq-ce:latest
    ports:
      - "1883:1883"
    networks:
      - network

  mqtt-cli: # For data collection simulations.
    container_name: mqtt-cli
    image: hivemq/mqtt-cli
    networks:
      - network
    depends_on:
      - broker