# Generated by Django 5.0.1 on 2024-01-20 14:15

from django.db import migrations, models


def register_model(apps, schema_editor):
    SessionQueries = apps.get_model('session', 'SessionQueries')
    SessionQueries.objects.create()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_temperature_chart_query',
                 models.CharField(choices=[('hour', 'hour'), ('day', 'day'), ('week', 'week')], max_length=4,
                                  null=True)),
                ('last_humidity_chart_query',
                 models.CharField(choices=[('hour', 'hour'), ('day', 'day'), ('week', 'week')], max_length=4,
                                  null=True)),
                ('last_noise_level_chart_query',
                 models.CharField(choices=[('hour', 'hour'), ('day', 'day'), ('week', 'week')], max_length=4,
                                  null=True)),
                ('last_heart_frequency_chart_query',
                 models.CharField(choices=[('hour', 'hour'), ('day', 'day'), ('week', 'week')], max_length=4,
                                  null=True)),
                ('last_report_query', models.CharField(null=True)),
            ],
        ),
        migrations.RunPython(register_model),
    ]
