# Generated by Django 5.0.1 on 2024-01-29 20:20

from django.db import migrations, models


def register_model(apps, schema_editor):
    LastRecordedSensorData = apps.get_model('sensor_data', 'LastRecordedSensorData')
    LastRecordedSensorData.objects.create(heart_frequency=85)


class Migration(migrations.Migration):
    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRecordedSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_frequency', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(register_model),
    ]
