# Generated by Django 5.0.1 on 2024-01-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_rename_environmentaldata_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='heart_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
